language: r
sudo: false
cache: packages

warnings_are_errors: true

matrix:
  include:
    - os: linux
      language: r
      compiler: gcc
      addons:
        apt:
          packages:
          - libgsl0-dev
      r_binary_packages:
        covr
      after_success:
        - Rscript -e 'library(covr);codecov()'
      env: TRAVIS_LANG=R     
    
    - os: linux
      language: r
      compiler: clang
      addons:
        apt:
          packages:
          - libgsl0-dev
      r_binary_packages:
        covr
      after_success:
        - Rscript -e 'library(covr);codecov()'
      env: TRAVIS_LANG=R     
 
# remove cran check as it will fail because OpenMP 
#r_check_args: "--as-cran"

